### ISSUE TITLE
New UI links to empty console when parallel builds with multiple language versions

### ISSUE THREAD

**Issue by ghost** [DotCi/DotCiInstallPackages#3]
#### Summary

I suspect multiple language version along with multiple parallel run creates a new UI rendering confusion that leads to bad URL link generation. 
#### Problem

I'm not sure where **dotCI** came from the generation of _https://dotci/job/foo/job/bar/3/dotCIdub1_production URL_ from new UI. But that link has no console output.

However when toggling back to the old UI view I get instead get a working _https://dotci/job/foo/job/bar/3/language_version=v0.10.41p1,script=dub1_production/console_
#### Observation

This makes sense when you compare the successful OLD UI view of 
![screen shot 2016-03-08 at 12 25 08 pm](https://cloud.githubusercontent.com/assets/566629/13611567/e19f8e0a-e528-11e5-850e-fc884b622a99.png)

versus the failed New UI view of 
![screen shot 2016-03-08 at 12 32 13 pm](https://cloud.githubusercontent.com/assets/566629/13611785/d39fff00-e529-11e5-89a4-a966b60e1b7a.png)

where .ci.yml is

```
environment:
  language: node
  language_versions:
    - v0.10.41p1
    - v4.2.3

build:
  run:
    snc1_staging:
      - baz

    snc1_production:
      - baz

    dub1_production:
      - baz
```
